### PR TITLE
Show/hide password on login page

### PR DESCRIPTION
**Pull request by sinisaos**
Related to #309

### CODE REVIEW

**Comment by sinisaos** [comment]
> There's one thing which I'm a bit worried about though. When the password is saved by Chrome, someone can click the eye, and see the saved password. It seems like a security problem, because if someone gained quick access to a user's computer they could get their password.
> 
> But having said that, you can get it using JavaScript like this:
> 
> ```js
> document.querySelector('input[name=password]').value
> ```
> 
> So I'm not sure if we should have it on the login page - is it a security problem? I think it just highlights how problematic passwords are.

If someone got quick access to the user's computer, there's not much we can do (with or without show/hide password) because then it's easy to find the password with 
```js
document.querySelector('input[name=password]').value 
```
from the console, like you wrote or if the user has saved the password through the Chrome settings password manager.

If you're concerned about security risk, I'd close this PR as it's a minor (insignificant) change I've seen on many login forms and I don't think we should bother with it anymore. Do you agree with that?

**Comment by dantownsend** [comment]
> If someone got quick access to the user's computer, there's not much we can do (with or without show/hide password) because then it's easy to find the password with

I agree that if someone got access to someone's computer they're basically screwed anyway.

> If you're concerned about security risk, I'd close this PR as it's a minor (insignificant) change I've seen on many login forms and I don't think we should bother with it anymore. Do you agree with that?

I wouldn't close this PR - I prefer the new header style on the login page. I'm probably being overly cautious with the view password thing, as even Google does this:

Screenshot 2023-05-24 at 10 20 32

I'd definitely like it on the change password page.

**Comment by sinisaos** [comment]
> I wouldn't close this PR - I prefer the new header style on the login page. I'm probably being overly cautious with the view password thing, as even Google does this:

Yes exactly, even Google has it and I think they care about security. So we leave the current code? If yes, I will add new commit to show/hide password on the change password page.

**Comment by sinisaos** [comment]
@dantownsend I made a new commit with the changes to the password change page. I only `show/hide` the new password confirmation. Is that enough or should we enable `show/hide` on all three form fields?

**Comment by dantownsend** [comment]
I think we can make the password field as a separate component.

**Comment by sinisaos** [comment]
@dantownsend That's a great idea. I will make another commit with those changes. I hope it will be good enough.

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks. I haven't used v-model on custom components much before, but seems like a clean solution.

https://vuejs.org/guide/components/v-model.html

**Comment by sinisaos** [comment]
@dantownsend Great. This can be merged because everything works and looks good.

**Pull request merged**
