### PR TITLE
synchronise the filters with the GET parameters

### PR DESCRIPTION
**Pull request by sinisaos**
Related to #42 and #163

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend Did you have time to try this?

**Comment by dantownsend** [comment]
@sinisaos Not yet, will have a look today.

**Comment by dantownsend** [comment]
This is cool.

I came across an issue though - even though the values in the URL are applied as filters, they don't show in the filter sidebar for some reason.

https://user-images.githubusercontent.com/350976/172550468-d74f7d72-06a0-483e-9005-d9d3f19a1035.mov

I'm not sure why - will have to investigate more.

**Comment by sinisaos** [comment]
@dantownsend You're right. Sorry, I didn't watch it at all. I focused on being able to get back to the filtered view after pressing `Back` button.

**Comment by sinisaos** [comment]
@dantownsend Can you try this with last commit? It's keeping the form data after changing the route. Work with input type text and number, doesn't work on select.

**Comment by dantownsend** [comment]
Sorry I haven't had a change to look into this yet - will get it in the next release.

**Comment by sinisaos** [comment]
@dantownsend Another try with [history.state](https://developer.mozilla.org/en-US/docs/Web/API/History/state). The main problem is that the duration and keySearch widget are not in sync with `history.state`, so I changed that. The code is not the prettiest, but it works. Fell free to change that.


https://user-images.githubusercontent.com/30960668/180741650-a18b8785-dda9-48e1-a668-c8a8276eb299.mp4

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks - it looks like it works well in the video.

**Comment by sinisaos** [comment]
@dantownsend It works, but the code is not the nicest.

**Comment by dantownsend** [comment]
Still valid - just need to test it.

**Comment by sinisaos** [comment]
Unfortunately, this no longer works. Need to find another way to synchronize the query parameters and the filter form

**Pull request closed without merging**
