### PR TITLE
made the RowListing page work with custom PK name

### PR DESCRIPTION
**Pull request by dantownsend**
Related to https://github.com/piccolo-orm/piccolo_admin/issues/81

This fixes the listing page when the table has a custom PK column name.

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend This looks great. Just one question. Will you make changes to `EditRow.vue` and all the editing components in this PR or will you make a separate PR for it?

**Comment by dantownsend** [comment]
@sinisaos Thanks. I think the outstanding issues are with the foreign key selector, but there may be others.

I'll see if I have time later to fix the others. Otherwise I'll release this partial fix.

**Comment by sinisaos** [comment]
@dantownsend To solve foreign key selector we need to change this line https://github.com/piccolo-orm/piccolo_api/blob/caa8d7f21b51b6fdfdfdf527d873ded2c0316afc/piccolo_api/crud/endpoints.py#L427
in Piccolo API to this so the `api/tables/some-table/ids/` endpoint can return `primary key` as int,str or uuid and that work fine.

```python
return JSONResponse(
    {
        str(i[self.table._meta.primary_key._meta.name]): i[
            "readable"
        ]
        for i in values
    }
)
```
But that is unfortunately a minor part of the problem. As I already wrote, this is not an easy task because the whole concept of `crud` operations and `relations` between tables is based on `Serial` type, and we need to change all crud methods (that contain `row_id`) in the Piccolo API to be able to use it in Piccolo Admin.

**Comment by dantownsend** [comment]
@sinisaos Yes, I see what you're saying. I think it's fixable - looking now.

**Comment by dantownsend** [comment]
@sinisaos I've opened two more PRs. Combined with this one, it seems to fix the foreign key selector:

https://github.com/piccolo-orm/piccolo/pull/392
https://github.com/piccolo-orm/piccolo_api/pull/132

**Comment by sinisaos** [comment]
@dantownsend Changes in the Piccolo API certainly solve the problem because I have already tried and tested it and everything work fine. Maybe it would be better to add `pk = UUID(primary_key=True)` to `Director` table because that table has a relation to `Movie` table and so you will be able to test if `FK` works. I did so. Custom `PK` in table without relations work fine, FK relation is problem.

**Comment by dantownsend** [comment]
@sinisaos If you pull the latest from this branch, I've added a foreign key from Movie to Studio, so it can be tested properly.

**Comment by sinisaos** [comment]
@dantownsend I already wrote this in Piccolo ORM pull request but WELL DONE AGAIN. Now with dynamic `value_type` for FK everything work great. All crud methods (without need to changes in Piccolo API) with or without FK relations, filtering etc. work great. Great. I think that will be it.

**Comment by sinisaos** [comment]
@dantownsend Sorry to write like this in comment, but can you also change `RowSortModal.vue` to something like this that sorting also works with custom PK. Thanks.

```vue
<template>
    <Modal v-on:close="$emit('close')">
        <template v-if="schema">
            <p>Sort by:</p>

            <select name="property" v-model="propertyName">
                <option :value="propertyName">
                    {{ propertyName }}
                </option>

                <option
                    :key="key"
                    :value="key"
                    v-for="(property, key) in schema.properties"
                >
                    {{ key }}
                </option>
            </select>

            <select name="ordering" v-model="ascending">
                <option value="ascending">Ascending</option>
                <option value="descending">Descending</option>
            </select>

            <button v-on:click.prevent="save">Sort</button>
        </template>
    </Modal>
</template>

<script lang="ts">
import Modal from "./Modal.vue"
import * as i from "../interfaces"

export default {
    props: {
        schema: Object,
        tableName: String
    },
    data() {
        return {
            ascending: "descending",
            propertyName: this.schema["primary_key_name"]
        }
    },
    components: {
        Modal
    },
    methods: {
        async save() {
            let config: i.SortByConfig = {
                property: this.propertyName,
                ascending: this.ascending == "ascending"
            }
            this.$store.commit("updateSortBy", config)

            await this.$store.dispatch("fetchRows")

            this.$emit("close")
        }
    },
    mounted() {
        let sortBy: i.SortByConfig | null = this.$store.state.sortBy
        if (sortBy) {
            this.ascending = sortBy.ascending ? "ascending" : "descending"
            this.propertyName = sortBy.property
        }
    }
}
</script>

<style>
</style>
```

**Comment by dantownsend** [comment]
@sinisaos Thanks very much. I'll make the last changes you suggested and will release later tonight or in the morning.

**Comment by sinisaos** [comment]
@dantownsend Great :+1: . I think everything should work. The first thing in the morning will be to check out the new version.

**Pull request merged**
