### PR TITLE
fix clear filters for duration widget

### PR DESCRIPTION
**Pull request by sinisaos**
Small fix for clear filters in `RowFilter.vue`. Duration widget are not properly cleaned. Now all fields is properly cleaned.

### CODE REVIEW

**Comment by dantownsend** [comment]
@sinisaos Thanks for this.

I didn't realise that when you do `form.clear()`, it doesn't work on hidden inputs for some reason, and that's what the `DurationWidget` uses.

https://stackoverflow.com/questions/2559616/javascript-true-form-reset-for-hidden-fields

In your code you explicitly reset a few different field types in the for-loop - do you think we need to, or is it enough to just reset the hidden ones, as `form.reset` should've done it for the others?

Maybe we can just do this:

```javascript
[...form.elements].forEach((element) => {
    if (element.type == 'hidden') {
        element.value = ""
    }
})
```

**Comment by sinisaos** [comment]
@dantownsend Sorry for the late reply. You are absolutely right. I'm making changes with the second commit. Is it ok now?

**Comment by dantownsend** [comment]
@sinisaos Looks great, thanks!

It was such a subtle bug, I would never have found it if you hadn't noticed it.

**Comment by sinisaos** [comment]
@dantownsend I accidentally came on this problem. 
I think also see little bug with Flatpickr in edit form on [small screen](https://flatpickr.js.org/mobile-support/). When open edit form datetime field is empty (which led to error on form submit) and I think that we need to show Flatpickr widget also on mobile screen (not browser native date/time/datetime input like is now). 
We need changes something like this.
 ```
InputField.vue

<flat-pickr
 v-bind:config="{ enableTime: true, disableMobile: true }"
    v-bind:name="getFieldName(title)"
    v-model="localValue"
></flat-pickr>
```
What do you think?

**Comment by dantownsend** [comment]
@sinisaos Yes, you're right - I can replicate the problem on my phone.

Have you tried it with Flatpickr on mobile? Does it fit on the screen?

**Comment by sinisaos** [comment]
@dantownsend No. I tried on Chromium developer tools mobile devices screens. On this it's fit.

mobile

**Comment by dantownsend** [comment]
@sinisaos I tried it on the iOS simulator, for one of the smaller iPhones, and it fits OK.

Screenshot 2021-02-17 at 18 54 08

The UI feels a bit weird on iOS though. It seems fine on Android. It's better than not working though I guess.

I had a look for some alternative date time pickers, but couldn't find a good alternative. A lot of them only work on dates.

**Comment by sinisaos** [comment]
@dantownsend I agree with you. I also think we need to make this change because it’s better to have a working form with a slightly worse look (it's not that bad) than a form that doesn’t work well. Are you going to make a change or me?

**Comment by dantownsend** [comment]
@sinisaos I've just pushed the change - will release it shortly.

**Comment by sinisaos** [comment]
@dantownsend Great. I am also making some changes to the foreign key selection from issue [#30](https://github.com/piccolo-orm/piccolo_admin/issues/30). It's not the best quality code, but it's work. It is a search autocomplete without changes in the backend endpoint and without the use of `HTML select`. The biggest problem is that I can't get FK readable (`1` is displayed instead of `Peter Jackson`) in edit form. Tommorow I can paste code in issue comment that you can see what it is about. Cheers.

**Comment by dantownsend** [comment]
@sinisaos Sounds great, thanks.

**Pull request merged**
