### PR TITLE
Cypress file upload test

### PR DESCRIPTION
**Pull request by sinisaos**
Related to #216

### CODE REVIEW

**Comment by dantownsend** [comment]
Thanks for this. I wasn't sure how image uploading would work in Cypress, but seems to work well.

I made the file slightly smaller, and increased the timeout, just to give the file the best chance possible to finish uploading. On my local machine I have `example.py` configuered to upload files to S3, so is a bit slower.

**Comment by dantownsend** [comment]
Do you think it's worth adding a test for array columns which are using media storage?

**Comment by sinisaos** [comment]
Great, thanks I always forget to use smaller files. I tried it this morning and it works without problems thanks to the [selectFile](https://www.cypress.io/blog/2022/01/19/uploading-files-with-selectfile/) command. Previously, a plugin (cypress-file-upload plugin) should have been used.

**Comment by sinisaos** [comment]
> Do you think it's worth adding a test for array columns which are using media storage?

The file upload is the same for uploading single and multiple files (for Array column we also upload one file at a time), so I don't think there is a need for it.

**Comment by dantownsend** [comment]
OK, fair enough - lets merge this in.

**Pull request merged**
