### PR TITLE
adding wysiwyg editor

### PR DESCRIPTION
**Pull request by sinisaos**
Related to #152

### CODE REVIEW

**Comment by dantownsend** [comment]
Cool, thanks for this.

**Comment by sinisaos** [comment]
I always forget about dark mode :). I didn't find a dark mode for Quill, so I will have to find svg css classes and change them for dark mode. 

> Other than that my only concern is it locks us to Vue 2. When we move to Vue 3 we will have to find a different library.

Because we use the hidden textarea to submit content, everything will be fine and the transition should not be difficult. We only need to find widget for Vue3 that suit us. The are several option like several options like [CKEditor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html) or [vue-quill](https://github.com/vueup/vue-quill).

**Comment by sinisaos** [comment]
Is this okay?

dark

**Comment by dantownsend** [comment]
@sinisaos Yes, that looks great

**Comment by sinisaos** [comment]
@dantownsend Can you add docs for `rich_text_columns` with screenshots? I don't have a Safari and it would be nice if the screenshots is from the same browser.

**Comment by dantownsend** [comment]
Yeah, I'll try and add the docs and screenshots today.

**Comment by dantownsend** [comment]
I had a look at the new bundle size with the WYSIWYG library included - chunk-vendors.js went up around 300 kB (ignore the blue highlighted lines):

Screenshot 2022-04-03 at 20 17 41
Screenshot 2022-04-03 at 20 15 51

It might be worth doing some testing on Chrome with network throttling enabled. What do you think?

There are some [smaller editors](https://github.com/jaredreich/pell#comparisons), but they don't seem as nice as Quill.

**Comment by sinisaos** [comment]
@dantownsend Chromium DevTools results:
```
Without wysiwyg editor (hard refresh - no cache) size is 300 kb:
Mid-tier mobile 3.12 s
Low-end mobile 11.22 s

With wysiwyg editor (hard refresh - no cache) size is 600 kb:
Mid-tier mobile 4.69 s
Low-end mobile 16.79 s
```
Feel free to implement another editor (Pell have also [Vue implementation](https://github.com/jaredreich/pell/blob/v2/examples/vue.md)).I basically chose vue2-editor because it is easy to implement, and Quill is among the most popular and most frequently used editors. Rich Text Editor is just an optional feature I've seen with other admin interfaces.

**Comment by dantownsend** [comment]
@sinisaos Thanks for checking that. 

Let's just release it. I think it's a good feature, and we can always swap in a different editor in the future.

**Pull request merged**
